### ISSUE TITLE
Room Structure

### ISSUE THREAD

**Issue by agahEbrahimi** [ArchWoodson/projecteers-arch#23]
A list containing all the features that a room has should be compiled. 
This list includes factors such as: 
- Rooms connected to
- Name 
- Frequency of usage in database
- Square footage percentage Average: The average SqF of that Room within the Database (In percentage form)

**Comment by SirMathhman** [comment]
1) Done
2) Done
3) Done
4) Done

**Comment by SirMathhman** [comment]
WHAT ELSE DO YOU WANT FROM ME?!?!?!?!
